services:
  - type: web
    name: authproject
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: gunicorn AuthProject.wsgi:application
