services:
  - type: web
    name: authproject
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: "gunicorn AuthProject.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: authproject.onrender.com,localhost,127.0.0.1
databases:
  - name: postgres
    plan: free
    ipAllowList: []
